---
- name: set docker repo
  copy:
    src: files/docker-ce.repo
    dest: /etc/yum.repos.d/
- name: install docker and tools
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
- name: enable and start docker
  service:
    name: docker
    enabled: true
    state: started
- name: download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
