---
- name: create LXC container using proxmox api
  hosts: localhost
  connection: local
  tasks:
# Variable location is located on group_vars/all.yml
# Template for creating a server via ansible is below:
#  - name: Template for creating a server
#    include_role:
#      name: create-server
#    vars: ## Server defaults
#      server_vmid: 100
#      server_hostname: default.sandbox.io
#      server_netif: '{"net0":"name=eth0,ip=dhcp,bridge=vmbr0"}' ## add hwaddr for custom MAC address
#      server_ostemplate: rockylinux-8-default_20210929_amd64.tar.xz
#      server_memory: 512
#      server_swap: 256
#      server_disk: 5
#      server_cores: 1
#      keyctl_status: false
#      unprivileged_status: true
  - name: create gateway server 
    include_role:
      name: create-server
    vars:
      server_vmid: "{{ gateway_vmid }}"
      server_hostname: "{{ gateway_hostname }}"
      server_netif: "{{ gateway_netif }}"
      server_nameserver: "{{ gateway_nameserver }}"
- name: pve connection to setup rockylinux
  hosts: pve
  tasks:
  - name: define include role for loop
    include_role:
      name: setup-ssh
    vars:
      vmid: "{{ item }}"
    with_items:
     - "{{ gateway_vmid }}"
# In order for sshd to be available on created server, you need to add the server vmid to the loop function:
#     - "{{ some_server_vmid }}"
...
