---
- name: check ban
  hosts: pve
  tasks:
  - name: setup ssh for jenkins service
    include_role:
      name: setup-ssh
    vars:
      vmid: "{{ jenkins_vmid }}"
- name: setup jenkins server
  hosts: jenkins
  tasks:
  - name: include_role for jenkins setup
    include_role:
      name: setup-jenkins
