---
- name: installation of sshd as lxc dont have ssh installed
  hosts: pve
  tasks:
  - name: include_role of setup-ssh
    include_role:
      name: setup-ssh
    vars:
      vmid: "{{ gateway_vmid }}"
- name: Setup gateway for playground dhcp and dns configuration
  hosts: gateway
  tasks:
  - name: setup gateway using role
    include_role:
      name: setup-gateway
